### ISSUE TITLE
Create first draft of language specification

### ISSUE THREAD

**Issue by bytorbrynden** [Gigabyte-Giant/Burst#1]
The language specification will be used to provide a medium-level overview of the language. It will describe different things about the language, such as its keywords, operators, and more.

Before we can start implementing the Burst language, we need a good idea as to what the language will be.

The language specification document, can be found [here](https://docs.google.com/document/d/1qarMBStFDTrukvj9EFeA_-2ozHZa6giRhpnRD8tBjVE/edit?usp=sharing).
### Tasks
- [x] Draft the lifecycle of a Burst program
- [x] Draft an overview as to how the lexer will work
- [ ] Draft an overview as to how the type checker will work
- [ ] Draft an overview as to how the parser will work
- [ ] Draft an overview as to how the interpreter will work
- [x] Explain terms
  - [x] Single Token
  - [x] Combined Token

/cc @BurstLanguage/spec

**Comment by bytorbrynden** [comment]
...one thing I'd like to note, is that all overviews that are contained within the language specification, will be fairly high-level.

More detailed explanations of how things work, will eventually be provided in general code base documentation.

**Comment by bytorbrynden** [comment]
So far, the lexer has a fairly good overview, so I'm going to go ahead and start implementing that. As the language specification changes, I'll make sure all the necessary changes are made to the implementation(s).

**Comment by bytorbrynden** [comment]
As of today, the language specification is being maintained by @BurstLanguage/spec, under a GitHub repository ([BurstLanguage/Language-Specification]).

All content relating to the language specification, shall be placed in its respective place in that repository.

I will be transferring this issue, to that repository.
